plugins { id 'application' }
java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }
dependencies {
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'com.formdev:flatlaf:3.7'
    implementation 'net.fabricmc:fabric-loader:0.19.5'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
repositories { maven { url = 'https://maven.fabricmc.net/' } }
sourceSets.main.java.srcDir '../common/src/main/java'
application { mainClass = 'dev.tarclient.launcher.TarLauncher' }
processResources {
    dependsOn ':client-mod:remapJar'
    from(project(':client-mod').tasks.named('remapJar')) {
        into 'bundled'
        rename { 'tar-client.jar' }
    }
}
test { useJUnitPlatform() }
tasks.register('fatJar', Jar) {
    archiveFileName = 'tar-launcher.jar'
    manifest { attributes 'Main-Class': application.mainClass.get() }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from sourceSets.main.output
    dependsOn configurations.runtimeClasspath
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    exclude 'META-INF/*.SF', 'META-INF/*.RSA', 'META-INF/*.DSA', 'module-info.class'
}
